# documents: https://statements-manager.readthedocs.io/ja/stable/problem_config.html

id = "G"
params_path = "./tests/constraints.hpp"
#assets_path = "./statement/assets/"
sample_path = "./tests/"
ignore_samples = []

[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]

[constraints]
MIN_N = 4
MAX_N = 20000
MIN_Q = 1
MAX_Q = 20000

[mofe]
problem_id = 303
difficulty = "ผักชี" # "Milk", "Assam", "Benihuki", "Ceylon", "Darjeeling", "Earlgray", "Flavor", "ผักชี"
submission_limit_1 = 5
submission_limit_2 = 60

[[mofe.testcase_sets.sample]]
regex = "00_sample_\\d+"
points = 0

[[mofe.testcase_sets.all]]
regex = "."
points = 100