# documents: https://statements-manager.readthedocs.io/ja/stable/problem_config.html

id = "D" # コンテスト内での問題 ID

# --- ここから ---
params_path = "./tests/constraints.h"
#assets_path = "./statement/assets/"
sample_path = "./tests/"
ignore_samples = []

[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]
# --- ここまでの部分はあんまり書き換えないでください ---

# 問題の制約
[constraints]
const long long A_MIN = -1e18;
const long long A_MAX = 1e18;
const int 		T_MIN = 1;
const int 		T_MAX = 1e5;
const int 		X_MIN = 1;
const int 		X_MAX = 4;
const int 		Y_MIN = 1;
const int 		Y_MAX = 4;
const int 		R_MIN = 1;
const int 		R_MAX = 4;

[mofe]
problem_id = 9999 # MOFE 上での問題 ID
difficulty = "Benihuki" # 問題の難易度、 "Milk", "Assam", "Benihuki", "Ceylon", "Darjeeling", "Earlgray", "Flavor", "ผักชี" から選ぶ
execution_time_limit = 2000 # 実行時間制限 (ms)
submission_limit_1 = 5 # 1 回前の提出から何秒間隔を開ける必要があるか
submission_limit_2 = 60 # 2 回前の提出から何秒間隔を開ける必要があるか

[[mofe.testcase_sets.sample]]
regex = "04_sample" # sample のテストケースの名前にマッチする正規表現
points = 0 # sample ケースの配点

[[mofe.testcase_sets.all]]
regex = "." # all のテストケースの名前にマッチする正規表現
points = 100 # all ケースの配点