# documents: https://statements-manager.readthedocs.io/ja/stable/problem_config.html

id = "D" # コンテスト内での問題 ID

# --- ここから ---
params_path = "./tests/constraints.h"
#assets_path = "./statement/assets/"
sample_path = "./tests/"
ignore_samples = []

[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]
# --- ここまでの部分はあんまり書き換えないでください ---

# 問題の制約
[constraints]
A_MIN = -1000000000000000000
A_MAX = 1000000000000000000
T_MIN = 1
T_MAX = 100000
X_MIN = 1
X_MAX = 4
Y_MIN = 1
Y_MAX = 4
R_MIN = 1
R_MAX = 4

[mofe]
problem_id = 299 # MOFE 上での問題 ID
difficulty = "ผักชี" # 問題の難易度、 "Milk", "Assam", "Benihuki", "Ceylon", "Darjeeling", "Earlgray", "Flavor", "ผักชี" から選ぶ
execution_time_limit = 2000 # 実行時間制限 (ms)
submission_limit_1 = 5 # 1 回前の提出から何秒間隔を開ける必要があるか
submission_limit_2 = 60 # 2 回前の提出から何秒間隔を開ける必要があるか

[[mofe.testcase_sets.sample]]
regex = "00_sample_\\d+" # sample のテストケースの名前にマッチする正規表現
points = 0 # sample ケースの配点

[[mofe.testcase_sets.all]]
regex = "." # all のテストケースの名前にマッチする正規表現
points = 100 # all ケースの配点