// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int A_MIN = -1000000000000000000;
const long long int A_MAX = 1000000000000000000;
const long long int T_MIN = 1;
const long long int T_MAX = 30000;
const long long int X_MIN = 1;
const long long int X_MAX = 4;
const long long int Y_MIN = 1;
const long long int Y_MAX = 4;
const long long int R_MIN = 1;
const long long int R_MAX = 4;
