// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 4;
const long long int MAX_N = 40000;
const long long int MIN_Q = 1;
const long long int MAX_Q = 40000;
