// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int SUBTASK_MIN_N = 2;
const long long int SUBTASK_MAX_N = 20;
const long long int SUBTASK_MIN_M = 1;
const long long int SUBTASK_MAX_M = 100000;
const long long int SUBTASK_MIN_Q = 1;
const long long int SUBTASK_MAX_Q = 50000;
const long long int MIN_N = 2;
const long long int MAX_N = 1000000000;
const long long int MIN_M = 1;
const long long int MAX_M = 1000000000;
const long long int MIN_Q = 1;
const long long int MAX_Q = 50000;
