# documents: https://statements-manager.readthedocs.io/ja/stable/problem_config.html

id = "G" # コンテスト内での問題 ID

params_path = "./tests/constraints.hpp"
#assets_path = "./statement/assets/"
sample_path = "./tests/"
ignore_samples = []

[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]

# 問題の制約
[constraints]
T_MIN = 1
REG_MAX = 30
T_MAX = 100000
S_MAX = 1500000

[mofe]
problem_id = 304 # MOFE 上での問題 ID
difficulty = "ผักชี" # 問題の難易度、 "Milk", "Assam", "Benihuki", "Ceylon", "Darjeeling", "Earlgray", "Flavor", "ผักชี" から選ぶ
execution_time_limit = 2000 # 実行時間制限 (ms)
submission_limit_1 = 5 # 1 回前の提出から何秒間隔を開ける必要があるか
submission_limit_2 = 60 # 2 回前の提出から何秒間隔を開ける必要があるか

[[mofe.testcase_sets.sample]]
regex = "00_sample_\\d+" # sample のテストケースの名前にマッチする正規表現
points = 0 # sample ケースの配点

[[mofe.testcase_sets.all]]
regex = "." # all のテストケースの名前にマッチする正規表現
points = 100 # all ケースの配点
