name: Run test

on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '**.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - 'docs/**'

jobs:
  Rime-and-HTML-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      attestations: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Pull container image
        run: docker pull ghcr.io/tuatmcc/sakumon-image:latest
      - name: Rime test and filename check and html check
        run: docker run --rm -v $GITHUB_WORKSPACE:/root/app ghcr.io/tuatmcc/sakumon-image:latest /bin/zsh -c "cd /root/app && rime test --keep_going && python3 ./scripts/check_filename.py && python3 ./scripts/check_html.py"
