name: Run test

on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '**.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - 'docs/**'

jobs:
  Rime-and-HTML-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: sakumon
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Rime test and filename check and html check
      run: docker run --rm -v $GITHUB_WORKSPACE:/root/app sakumon /bin/zsh -c "cd /root/app && rime test --keep_going && uv run --python python3.10 ./scripts/check_filename.py && uv run --python python3.10 ./scripts/check_html.py"
