name: Run test

on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '**.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - 'docs/**'

jobs:
  Rime-and-HTML-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tuatmcc/sakumon-image:latest
      volumes:
        - /github/workspace:/root/app
    permissions:
      contents: read
      packages: read
      attestations: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Working Directory
        run: cd /root/app

      - name: Rime test
        run: rime test --keep_going --jobs 4

      - name: Check filenames
        run: python3 scripts/check_filename.py

      - name: Check HTMLs
        run: python3 scripts/check_html.py

      - name: Upload Rime Output
        uses: actions/upload-artifact@v4
        with:
          name: rime-out
          retention-days: 7
          path: |
            **/rime-out/
            !**/rime-out/**/**.exe